spring.application.name=AWN Dashboards

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-tiny-darkness-aoev5pei.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_flAc1Ha5mMOW}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect